version: '3'
services:
  peoplefirst:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: PeopleFirst
    networks:
      - peoplefirst
    ports:
      - '3000:3000'
    environment:
     - HOST=0.0.0.0
    command: npm run start
networks:
  peoplefirst:
    driver: bridge
