# Usage:
#
#    Build image:
#    docker build -t peoplefirst .
#
#    Run image (on localhost:8080):
#    docker run --name peoplefirst -p 8080:80 peoplefirst
#
#    Run image as virtual host (read more: https://github.com/jwilder/nginx-proxy):
#    docker run -e VIRTUAL_HOST=peoplefirst.your-domain.com --name peoplefirst peoplefirst

FROM node:8.9.4-alpine as builder

COPY package.json ./

## Storing node modules on a separate layer will prevent unnecessary npm installs at each build
RUN npm i && mkdir /ng-app && mv ./node_modules ./ng-app

WORKDIR /ng-app

COPY . .
